# Generated by Django 5.2.5 on 2025-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
