# Generated by Django 5.2.5 on 2025-09-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0003_alter_about_mobile_alter_about_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_image',
        ),
    ]
